# generated by datamodel-codegen:
#   filename:  api-docs/models/Agent.json
#   timestamp: 2023-10-15T19:00:16+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, constr


class Agent(BaseModel):
    accountId: Optional[constr(min_length=1)] = Field(
        None,
        description="Account ID that is tied to this agent. Only included on your own agent.",
    )
    symbol: constr(min_length=3, max_length=14) = Field(
        ..., description="Symbol of the agent."
    )
    headquarters: constr(min_length=1) = Field(
        ..., description="The headquarters of the agent."
    )
    credits: int = Field(
        ...,
        description="The number of credits the agent has available. Credits can be negative if funds have been overdrawn.",
    )
    startingFaction: constr(min_length=1) = Field(
        ..., description="The faction the agent started with."
    )
    shipCount: Optional[int] = Field(
        None, description="How many ships are owned by the agent."
    )
