# generated by datamodel-codegen:
#   filename:  api-docs/models/Chart.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class Chart(BaseModel):
    waypointSymbol: Optional[str] = Field(
        None, description='The symbol of the waypoint.'
    )
    submittedBy: Optional[str] = Field(
        None, description='The agent that submitted the chart for this waypoint.'
    )
    submittedOn: Optional[datetime] = Field(
        None, description='The time the chart for this waypoint was submitted.'
    )
