# generated by datamodel-codegen:
#   filename:  api-docs/models/ContractPayment.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ContractPayment(BaseModel):
    onAccepted: int = Field(
        ...,
        description='The amount of credits received up front for accepting the contract.',
    )
    onFulfilled: int = Field(
        ...,
        description='The amount of credits received when the contract is fulfilled.',
    )
