# generated by datamodel-codegen:
#   filename:  api-docs/models/FactionTrait.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from pydantic import BaseModel, Field
from typing_extensions import Literal


class FactionTrait(BaseModel):
    symbol: Literal[
        'BUREAUCRATIC',
        'SECRETIVE',
        'CAPITALISTIC',
        'INDUSTRIOUS',
        'PEACEFUL',
        'DISTRUSTFUL',
        'WELCOMING',
        'SMUGGLERS',
        'SCAVENGERS',
        'REBELLIOUS',
        'EXILES',
        'PIRATES',
        'RAIDERS',
        'CLAN',
        'GUILD',
        'DOMINION',
        'FRINGE',
        'FORSAKEN',
        'ISOLATED',
        'LOCALIZED',
        'ESTABLISHED',
        'NOTABLE',
        'DOMINANT',
        'INESCAPABLE',
        'INNOVATIVE',
        'BOLD',
        'VISIONARY',
        'CURIOUS',
        'DARING',
        'EXPLORATORY',
        'RESOURCEFUL',
        'FLEXIBLE',
        'COOPERATIVE',
        'UNITED',
        'STRATEGIC',
        'INTELLIGENT',
        'RESEARCH_FOCUSED',
        'COLLABORATIVE',
        'PROGRESSIVE',
        'MILITARISTIC',
        'TECHNOLOGICALLY_ADVANCED',
        'AGGRESSIVE',
        'IMPERIALISTIC',
        'TREASURE_HUNTERS',
        'DEXTEROUS',
        'UNPREDICTABLE',
        'BRUTAL',
        'FLEETING',
        'ADAPTABLE',
        'SELF_SUFFICIENT',
        'DEFENSIVE',
        'PROUD',
        'DIVERSE',
        'INDEPENDENT',
        'SELF_INTERESTED',
        'FRAGMENTED',
        'COMMERCIAL',
        'FREE_MARKETS',
        'ENTREPRENEURIAL',
    ] = Field(..., description='The unique identifier of the trait.')
    name: str = Field(..., description='The name of the trait.')
    description: str = Field(..., description='A description of the trait.')
