# generated by datamodel-codegen:
#   filename:  api-docs/models/Faction.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field, RootModel, constr
from typing_extensions import Literal


class FactionSymbols(
    RootModel[
        Literal[
            'COSMIC',
            'VOID',
            'GALACTIC',
            'QUANTUM',
            'DOMINION',
            'ASTRO',
            'CORSAIRS',
            'OBSIDIAN',
            'AEGIS',
            'UNITED',
            'SOLITARY',
            'COBALT',
            'OMEGA',
            'ECHO',
            'LORDS',
            'CULT',
            'ANCIENTS',
            'SHADOW',
            'ETHEREAL',
        ]
    ]
):
    root: Literal[
        'COSMIC',
        'VOID',
        'GALACTIC',
        'QUANTUM',
        'DOMINION',
        'ASTRO',
        'CORSAIRS',
        'OBSIDIAN',
        'AEGIS',
        'UNITED',
        'SOLITARY',
        'COBALT',
        'OMEGA',
        'ECHO',
        'LORDS',
        'CULT',
        'ANCIENTS',
        'SHADOW',
        'ETHEREAL',
    ] = Field(..., description='The symbol of the faction.', examples=['COSMIC'])


class FactionTrait(BaseModel):
    symbol: Literal[
        'BUREAUCRATIC',
        'SECRETIVE',
        'CAPITALISTIC',
        'INDUSTRIOUS',
        'PEACEFUL',
        'DISTRUSTFUL',
        'WELCOMING',
        'SMUGGLERS',
        'SCAVENGERS',
        'REBELLIOUS',
        'EXILES',
        'PIRATES',
        'RAIDERS',
        'CLAN',
        'GUILD',
        'DOMINION',
        'FRINGE',
        'FORSAKEN',
        'ISOLATED',
        'LOCALIZED',
        'ESTABLISHED',
        'NOTABLE',
        'DOMINANT',
        'INESCAPABLE',
        'INNOVATIVE',
        'BOLD',
        'VISIONARY',
        'CURIOUS',
        'DARING',
        'EXPLORATORY',
        'RESOURCEFUL',
        'FLEXIBLE',
        'COOPERATIVE',
        'UNITED',
        'STRATEGIC',
        'INTELLIGENT',
        'RESEARCH_FOCUSED',
        'COLLABORATIVE',
        'PROGRESSIVE',
        'MILITARISTIC',
        'TECHNOLOGICALLY_ADVANCED',
        'AGGRESSIVE',
        'IMPERIALISTIC',
        'TREASURE_HUNTERS',
        'DEXTEROUS',
        'UNPREDICTABLE',
        'BRUTAL',
        'FLEETING',
        'ADAPTABLE',
        'SELF_SUFFICIENT',
        'DEFENSIVE',
        'PROUD',
        'DIVERSE',
        'INDEPENDENT',
        'SELF_INTERESTED',
        'FRAGMENTED',
        'COMMERCIAL',
        'FREE_MARKETS',
        'ENTREPRENEURIAL',
    ] = Field(..., description='The unique identifier of the trait.')
    name: str = Field(..., description='The name of the trait.')
    description: str = Field(..., description='A description of the trait.')


class Faction(BaseModel):
    symbol: FactionSymbols = Field(..., description='Faction symbol.')
    name: constr(min_length=1) = Field(..., description='Name of the faction.')
    description: constr(min_length=1) = Field(
        ..., description='Description of the faction.'
    )
    headquarters: constr(min_length=1) = Field(
        ..., description="The waypoint in which the faction's HQ is located in."
    )
    traits: List[FactionTrait] = Field(
        ..., description='List of traits that define this faction.'
    )
    isRecruiting: bool = Field(
        ...,
        description='Whether or not the faction is currently recruiting new agents.',
    )
