# generated by datamodel-codegen:
#   filename:  api-docs/models/Meta.json
#   timestamp: 2023-10-15T19:00:16+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, conint


class Meta(BaseModel):
    total: conint(ge=0) = Field(
        ..., description="Shows the total amount of items of this kind that exist."
    )
    page: conint(ge=1) = Field(
        ...,
        description="A page denotes an amount of items, offset from the first item. Each page holds an amount of items equal to the `limit`.",
    )
    limit: conint(ge=1, le=20) = Field(
        ...,
        description="The amount of items in each page. Limits how many items can be fetched at once.",
    )
