# generated by datamodel-codegen:
#   filename:  api-docs/models/ScannedSystem.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel, constr
from typing_extensions import Literal


class SystemType(
    RootModel[
        Literal[
            'NEUTRON_STAR',
            'RED_STAR',
            'ORANGE_STAR',
            'BLUE_STAR',
            'YOUNG_STAR',
            'WHITE_DWARF',
            'BLACK_HOLE',
            'HYPERGIANT',
            'NEBULA',
            'UNSTABLE',
        ]
    ]
):
    root: Literal[
        'NEUTRON_STAR',
        'RED_STAR',
        'ORANGE_STAR',
        'BLUE_STAR',
        'YOUNG_STAR',
        'WHITE_DWARF',
        'BLACK_HOLE',
        'HYPERGIANT',
        'NEBULA',
        'UNSTABLE',
    ] = Field(..., description='The type of waypoint.')


class ScannedSystem(BaseModel):
    symbol: constr(min_length=1) = Field(..., description='Symbol of the system.')
    sectorSymbol: constr(min_length=1) = Field(
        ..., description="Symbol of the system's sector."
    )
    type: SystemType
    x: int = Field(..., description='Position in the universe in the x axis.')
    y: int = Field(..., description='Position in the universe in the y axis.')
    distance: int = Field(
        ..., description="The system's distance from the scanning ship."
    )
