# generated by datamodel-codegen:
#   filename:  api-docs/models/ScannedSystem.json
#   timestamp: 2023-10-15T19:00:16+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, constr


class SystemType(Enum):
    NEUTRON_STAR = "NEUTRON_STAR"
    RED_STAR = "RED_STAR"
    ORANGE_STAR = "ORANGE_STAR"
    BLUE_STAR = "BLUE_STAR"
    YOUNG_STAR = "YOUNG_STAR"
    WHITE_DWARF = "WHITE_DWARF"
    BLACK_HOLE = "BLACK_HOLE"
    HYPERGIANT = "HYPERGIANT"
    NEBULA = "NEBULA"
    UNSTABLE = "UNSTABLE"


class ScannedSystem(BaseModel):
    symbol: constr(min_length=1) = Field(..., description="Symbol of the system.")
    sectorSymbol: constr(min_length=1) = Field(
        ..., description="Symbol of the system's sector."
    )
    type: SystemType
    x: int = Field(..., description="Position in the universe in the x axis.")
    y: int = Field(..., description="Position in the universe in the y axis.")
    distance: int = Field(
        ..., description="The system's distance from the scanning ship."
    )
