# generated by datamodel-codegen:
#   filename:  api-docs/models/ShipyardTransaction.json
#   timestamp: 2023-10-15T19:00:16+00:00

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field, conint


class ShipyardTransaction(BaseModel):
    waypointSymbol: str = Field(
        ..., description="The symbol of the waypoint where the transaction took place."
    )
    shipSymbol: str = Field(
        ...,
        description="The symbol of the ship that was the subject of the transaction.",
    )
    price: conint(ge=0) = Field(..., description="The price of the transaction.")
    agentSymbol: str = Field(
        ..., description="The symbol of the agent that made the transaction."
    )
    timestamp: datetime = Field(..., description="The timestamp of the transaction.")
