# generated by datamodel-codegen:
#   filename:  api-docs/models/ShipModificationTransaction.json
#   timestamp: 2023-10-15T19:00:16+00:00

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field, conint


class ShipModificationTransaction(BaseModel):
    waypointSymbol: str = Field(
        ..., description="The symbol of the waypoint where the transaction took place."
    )
    shipSymbol: str = Field(
        ..., description="The symbol of the ship that made the transaction."
    )
    tradeSymbol: str = Field(..., description="The symbol of the trade good.")
    totalPrice: conint(ge=0) = Field(
        ..., description="The total price of the transaction."
    )
    timestamp: datetime = Field(..., description="The timestamp of the transaction.")
