# generated by datamodel-codegen:
#   filename:  api-docs/models/ShipNavFlightMode.json
#   timestamp: 2023-10-15T19:00:16+00:00

from __future__ import annotations

from enum import Enum


class ShipNavFlightMode(Enum):
    DRIFT = "DRIFT"
    STEALTH = "STEALTH"
    CRUISE = "CRUISE"
    BURN = "BURN"
