# generated by datamodel-codegen:
#   filename:  api-docs/models/ShipNavStatus.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from pydantic import Field, RootModel
from typing_extensions import Literal


class ShipNavStatus(RootModel[Literal['IN_TRANSIT', 'IN_ORBIT', 'DOCKED']]):
    root: Literal['IN_TRANSIT', 'IN_ORBIT', 'DOCKED'] = Field(
        ..., description='The current status of the ship'
    )
