# generated by datamodel-codegen:
#   filename:  api-docs/models/ShipCondition.json
#   timestamp: 2023-10-15T19:00:16+00:00

from __future__ import annotations

from pydantic import Field, RootModel, conint


class ShipCondition(RootModel[conint(ge=0, le=100)]):
    root: conint(ge=0, le=100) = Field(
        ...,
        description="Condition is a range of 0 to 100 where 0 is completely worn out and 100 is brand new.",
    )
