# generated by datamodel-codegen:
#   filename:  api-docs/models/ShipType.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from pydantic import Field, RootModel
from typing_extensions import Literal


class ShipType(
    RootModel[
        Literal[
            'SHIP_PROBE',
            'SHIP_MINING_DRONE',
            'SHIP_INTERCEPTOR',
            'SHIP_LIGHT_HAULER',
            'SHIP_COMMAND_FRIGATE',
            'SHIP_EXPLORER',
            'SHIP_HEAVY_FREIGHTER',
            'SHIP_LIGHT_SHUTTLE',
            'SHIP_ORE_HOUND',
            'SHIP_REFINING_FREIGHTER',
        ]
    ]
):
    root: Literal[
        'SHIP_PROBE',
        'SHIP_MINING_DRONE',
        'SHIP_INTERCEPTOR',
        'SHIP_LIGHT_HAULER',
        'SHIP_COMMAND_FRIGATE',
        'SHIP_EXPLORER',
        'SHIP_HEAVY_FREIGHTER',
        'SHIP_LIGHT_SHUTTLE',
        'SHIP_ORE_HOUND',
        'SHIP_REFINING_FREIGHTER',
    ] = Field(..., description='Type of ship')
