# generated by datamodel-codegen:
#   filename:  api-docs/models/ShipFuel.json
#   timestamp: 2023-10-15T19:00:16+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field, conint


class Consumed(BaseModel):
    amount: conint(ge=0) = Field(
        ...,
        description="The amount of fuel consumed by the most recent transit or action.",
    )
    timestamp: datetime = Field(
        ..., description="The time at which the fuel was consumed."
    )


class ShipFuel(BaseModel):
    current: conint(ge=0) = Field(
        ..., description="The current amount of fuel in the ship's tanks."
    )
    capacity: conint(ge=0) = Field(
        ..., description="The maximum amount of fuel the ship's tanks can hold."
    )
    consumed: Optional[Consumed] = Field(
        None,
        description="An object that only shows up when an action has consumed fuel in the process. Shows the fuel consumption data.",
    )
