# generated by datamodel-codegen:
#   filename:  api-docs/models/ShipCargo.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field, conint


class ShipCargoItem(BaseModel):
    symbol: str = Field(
        ..., description='The unique identifier of the cargo item type.'
    )
    name: str = Field(..., description='The name of the cargo item type.')
    description: str = Field(..., description='The description of the cargo item type.')
    units: conint(ge=1) = Field(
        ..., description='The number of units of the cargo item.'
    )


class ShipCargo(BaseModel):
    capacity: conint(ge=0) = Field(
        ..., description='The max number of items that can be stored in the cargo hold.'
    )
    units: conint(ge=0) = Field(
        ..., description='The number of items currently stored in the cargo hold.'
    )
    inventory: List[ShipCargoItem] = Field(
        ..., description='The items currently in the cargo hold.'
    )
