# generated by datamodel-codegen:
#   filename:  api-docs/models/ShipFrame.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, RootModel, conint
from typing_extensions import Literal


class ShipCondition(RootModel[conint(ge=0, le=100)]):
    root: conint(ge=0, le=100) = Field(
        ...,
        description='Condition is a range of 0 to 100 where 0 is completely worn out and 100 is brand new.',
    )


class ShipRequirements(BaseModel):
    power: Optional[int] = Field(
        None, description='The amount of power required from the reactor.'
    )
    crew: Optional[int] = Field(
        None, description='The number of crew required for operation.'
    )
    slots: Optional[int] = Field(
        None, description='The number of module slots required for installation.'
    )


class ShipFrame(BaseModel):
    symbol: Literal[
        'FRAME_PROBE',
        'FRAME_DRONE',
        'FRAME_INTERCEPTOR',
        'FRAME_RACER',
        'FRAME_FIGHTER',
        'FRAME_FRIGATE',
        'FRAME_SHUTTLE',
        'FRAME_EXPLORER',
        'FRAME_MINER',
        'FRAME_LIGHT_FREIGHTER',
        'FRAME_HEAVY_FREIGHTER',
        'FRAME_TRANSPORT',
        'FRAME_DESTROYER',
        'FRAME_CRUISER',
        'FRAME_CARRIER',
    ] = Field(..., description='Symbol of the frame.')
    name: str = Field(..., description='Name of the frame.')
    description: str = Field(..., description='Description of the frame.')
    condition: Optional[ShipCondition] = None
    moduleSlots: conint(ge=0) = Field(
        ...,
        description='The amount of slots that can be dedicated to modules installed in the ship. Each installed module take up a number of slots, and once there are no more slots, no new modules can be installed.',
    )
    mountingPoints: conint(ge=0) = Field(
        ...,
        description='The amount of slots that can be dedicated to mounts installed in the ship. Each installed mount takes up a number of points, and once there are no more points remaining, no new mounts can be installed.',
    )
    fuelCapacity: conint(ge=0) = Field(
        ...,
        description='The maximum amount of fuel that can be stored in this ship. When refueling, the ship will be refueled to this amount.',
    )
    requirements: ShipRequirements
