# generated by datamodel-codegen:
#   filename:  api-docs/models/ShipRegistration.json
#   timestamp: 2023-10-15T19:00:16+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, constr


class ShipRole(Enum):
    FABRICATOR = "FABRICATOR"
    HARVESTER = "HARVESTER"
    HAULER = "HAULER"
    INTERCEPTOR = "INTERCEPTOR"
    EXCAVATOR = "EXCAVATOR"
    TRANSPORT = "TRANSPORT"
    REPAIR = "REPAIR"
    SURVEYOR = "SURVEYOR"
    COMMAND = "COMMAND"
    CARRIER = "CARRIER"
    PATROL = "PATROL"
    SATELLITE = "SATELLITE"
    EXPLORER = "EXPLORER"
    REFINERY = "REFINERY"


class ShipRegistration(BaseModel):
    name: constr(min_length=1) = Field(
        ..., description="The agent's registered name of the ship"
    )
    factionSymbol: constr(min_length=1) = Field(
        ..., description="The symbol of the faction the ship is registered with"
    )
    role: ShipRole
