# generated by datamodel-codegen:
#   filename:  api-docs/models/ShipNavRouteWaypoint.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel, constr
from typing_extensions import Literal


class WaypointType(
    RootModel[
        Literal[
            'PLANET',
            'GAS_GIANT',
            'MOON',
            'ORBITAL_STATION',
            'JUMP_GATE',
            'ASTEROID_FIELD',
            'NEBULA',
            'DEBRIS_FIELD',
            'GRAVITY_WELL',
        ]
    ]
):
    root: Literal[
        'PLANET',
        'GAS_GIANT',
        'MOON',
        'ORBITAL_STATION',
        'JUMP_GATE',
        'ASTEROID_FIELD',
        'NEBULA',
        'DEBRIS_FIELD',
        'GRAVITY_WELL',
    ] = Field(..., description='The type of waypoint.')


class ShipNavRouteWaypoint(BaseModel):
    symbol: constr(min_length=1) = Field(..., description='The symbol of the waypoint.')
    type: WaypointType
    systemSymbol: constr(min_length=1) = Field(
        ..., description='The symbol of the system the waypoint is in.'
    )
    x: int = Field(..., description='Position in the universe in the x axis.')
    y: int = Field(..., description='Position in the universe in the y axis.')
