# generated by datamodel-codegen:
#   filename:  api-docs/models/ShipMount.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field, conint
from typing_extensions import Literal


class ShipRequirements(BaseModel):
    power: Optional[int] = Field(
        None, description='The amount of power required from the reactor.'
    )
    crew: Optional[int] = Field(
        None, description='The number of crew required for operation.'
    )
    slots: Optional[int] = Field(
        None, description='The number of module slots required for installation.'
    )


class ShipMount(BaseModel):
    symbol: Literal[
        'MOUNT_GAS_SIPHON_I',
        'MOUNT_GAS_SIPHON_II',
        'MOUNT_GAS_SIPHON_III',
        'MOUNT_SURVEYOR_I',
        'MOUNT_SURVEYOR_II',
        'MOUNT_SURVEYOR_III',
        'MOUNT_SENSOR_ARRAY_I',
        'MOUNT_SENSOR_ARRAY_II',
        'MOUNT_SENSOR_ARRAY_III',
        'MOUNT_MINING_LASER_I',
        'MOUNT_MINING_LASER_II',
        'MOUNT_MINING_LASER_III',
        'MOUNT_LASER_CANNON_I',
        'MOUNT_MISSILE_LAUNCHER_I',
        'MOUNT_TURRET_I',
    ] = Field(..., description='Symbo of this mount.')
    name: str = Field(..., description='Name of this mount.')
    description: Optional[str] = Field(None, description='Description of this mount.')
    strength: Optional[conint(ge=0)] = Field(
        None,
        description="Mounts that have this value, such as mining lasers, denote how powerful this mount's capabilities are.",
    )
    deposits: Optional[
        List[
            Literal[
                'QUARTZ_SAND',
                'SILICON_CRYSTALS',
                'PRECIOUS_STONES',
                'ICE_WATER',
                'AMMONIA_ICE',
                'IRON_ORE',
                'COPPER_ORE',
                'SILVER_ORE',
                'ALUMINUM_ORE',
                'GOLD_ORE',
                'PLATINUM_ORE',
                'DIAMONDS',
                'URANITE_ORE',
                'MERITIUM_ORE',
            ]
        ]
    ] = Field(
        None,
        description='Mounts that have this value denote what goods can be produced from using the mount.',
    )
    requirements: ShipRequirements
