# generated by datamodel-codegen:
#   filename:  api-docs/models/ShipNavFlightMode.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from pydantic import Field, RootModel
from typing_extensions import Literal


class ShipNavFlightMode(RootModel[Literal['DRIFT', 'STEALTH', 'CRUISE', 'BURN']]):
    root: Literal['DRIFT', 'STEALTH', 'CRUISE', 'BURN'] = Field(
        ...,
        description="The ship's set speed when traveling between waypoints or systems.",
    )
