# generated by datamodel-codegen:
#   filename:  api-docs/models/ShipNavStatus.json
#   timestamp: 2023-10-15T19:00:16+00:00

from __future__ import annotations

from enum import Enum


class ShipNavStatus(Enum):
    IN_TRANSIT = "IN_TRANSIT"
    IN_ORBIT = "IN_ORBIT"
    DOCKED = "DOCKED"
