# generated by datamodel-codegen:
#   filename:  api-docs/models/ShipRegistration.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, RootModel, constr
from typing_extensions import Literal


class ShipRole(
    RootModel[
        Literal[
            'FABRICATOR',
            'HARVESTER',
            'HAULER',
            'INTERCEPTOR',
            'EXCAVATOR',
            'TRANSPORT',
            'REPAIR',
            'SURVEYOR',
            'COMMAND',
            'CARRIER',
            'PATROL',
            'SATELLITE',
            'EXPLORER',
            'REFINERY',
        ]
    ]
):
    root: Literal[
        'FABRICATOR',
        'HARVESTER',
        'HAULER',
        'INTERCEPTOR',
        'EXCAVATOR',
        'TRANSPORT',
        'REPAIR',
        'SURVEYOR',
        'COMMAND',
        'CARRIER',
        'PATROL',
        'SATELLITE',
        'EXPLORER',
        'REFINERY',
    ] = Field(..., description='The registered role of the ship')


class ShipRegistration(BaseModel):
    name: constr(min_length=1) = Field(
        ..., description="The agent's registered name of the ship"
    )
    factionSymbol: constr(min_length=1) = Field(
        ..., description='The symbol of the faction the ship is registered with'
    )
    role: ShipRole
