# generated by datamodel-codegen:
#   filename:  api-docs/models/Survey.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from datetime import datetime
from typing import List

from pydantic import BaseModel, Field, constr
from typing_extensions import Literal


class SurveyDeposit(BaseModel):
    symbol: str = Field(..., description='The symbol of the deposit.')


class Survey(BaseModel):
    signature: constr(min_length=1) = Field(
        ...,
        description='A unique signature for the location of this survey. This signature is verified when attempting an extraction using this survey.',
    )
    symbol: constr(min_length=1) = Field(
        ..., description='The symbol of the waypoint that this survey is for.'
    )
    deposits: List[SurveyDeposit] = Field(
        ...,
        description='A list of deposits that can be found at this location. A ship will extract one of these deposits when using this survey in an extraction request. If multiple deposits of the same type are present, the chance of extracting that deposit is increased.',
    )
    expiration: datetime = Field(
        ...,
        description='The date and time when the survey expires. After this date and time, the survey will no longer be available for extraction.',
    )
    size: Literal['SMALL', 'MODERATE', 'LARGE'] = Field(
        ...,
        description='The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.',
    )
