# generated by datamodel-codegen:
#   filename:  api-docs/models/SurveyDeposit.json
#   timestamp: 2023-10-15T19:00:16+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SurveyDeposit(BaseModel):
    symbol: str = Field(..., description="The symbol of the deposit.")
