# generated by datamodel-codegen:
#   filename:  api-docs/models/SystemType.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from pydantic import Field, RootModel
from typing_extensions import Literal


class SystemType(
    RootModel[
        Literal[
            'NEUTRON_STAR',
            'RED_STAR',
            'ORANGE_STAR',
            'BLUE_STAR',
            'YOUNG_STAR',
            'WHITE_DWARF',
            'BLACK_HOLE',
            'HYPERGIANT',
            'NEBULA',
            'UNSTABLE',
        ]
    ]
):
    root: Literal[
        'NEUTRON_STAR',
        'RED_STAR',
        'ORANGE_STAR',
        'BLUE_STAR',
        'YOUNG_STAR',
        'WHITE_DWARF',
        'BLACK_HOLE',
        'HYPERGIANT',
        'NEBULA',
        'UNSTABLE',
    ] = Field(..., description='The type of waypoint.')
