# generated by datamodel-codegen:
#   filename:  api-docs/models/WaypointOrbital.json
#   timestamp: 2023-10-21T17:38:30+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr


class WaypointOrbital(BaseModel):
    symbol: constr(min_length=1) = Field(
        ..., description='The symbol of the orbiting waypoint.'
    )
