# generated by datamodel-codegen:
#   filename:  api-docs/models/WaypointTrait.json
#   timestamp: 2023-10-21T17:38:31+00:00

from __future__ import annotations

from pydantic import BaseModel, Field
from typing_extensions import Literal


class WaypointTrait(BaseModel):
    symbol: Literal[
        'UNCHARTED',
        'MARKETPLACE',
        'SHIPYARD',
        'OUTPOST',
        'SCATTERED_SETTLEMENTS',
        'SPRAWLING_CITIES',
        'MEGA_STRUCTURES',
        'OVERCROWDED',
        'HIGH_TECH',
        'CORRUPT',
        'BUREAUCRATIC',
        'TRADING_HUB',
        'INDUSTRIAL',
        'BLACK_MARKET',
        'RESEARCH_FACILITY',
        'MILITARY_BASE',
        'SURVEILLANCE_OUTPOST',
        'EXPLORATION_OUTPOST',
        'MINERAL_DEPOSITS',
        'COMMON_METAL_DEPOSITS',
        'PRECIOUS_METAL_DEPOSITS',
        'RARE_METAL_DEPOSITS',
        'METHANE_POOLS',
        'ICE_CRYSTALS',
        'EXPLOSIVE_GASES',
        'STRONG_MAGNETOSPHERE',
        'VIBRANT_AURORAS',
        'SALT_FLATS',
        'CANYONS',
        'PERPETUAL_DAYLIGHT',
        'PERPETUAL_OVERCAST',
        'DRY_SEABEDS',
        'MAGMA_SEAS',
        'SUPERVOLCANOES',
        'ASH_CLOUDS',
        'VAST_RUINS',
        'MUTATED_FLORA',
        'TERRAFORMED',
        'EXTREME_TEMPERATURES',
        'EXTREME_PRESSURE',
        'DIVERSE_LIFE',
        'SCARCE_LIFE',
        'FOSSILS',
        'WEAK_GRAVITY',
        'STRONG_GRAVITY',
        'CRUSHING_GRAVITY',
        'TOXIC_ATMOSPHERE',
        'CORROSIVE_ATMOSPHERE',
        'BREATHABLE_ATMOSPHERE',
        'JOVIAN',
        'ROCKY',
        'VOLCANIC',
        'FROZEN',
        'SWAMP',
        'BARREN',
        'TEMPERATE',
        'JUNGLE',
        'OCEAN',
        'STRIPPED',
    ] = Field(..., description='The unique identifier of the trait.')
    name: str = Field(..., description='The name of the trait.')
    description: str = Field(..., description='A description of the trait.')
